### ISSUE TITLE
Quick Picker doesn't work with your extension

### ISSUE THREAD

**Issue by Bernd-L** [mtxr/vscode-sqltools#114]
### Issue Type

* [x] Bug
* [ ] Enhancement 
* [ ] Feature Request
* [x] Question
* [ ] Other

### Prerequisites (For bugfixes)

* [x] Are you running the latest version?
* [ ] Did you check the logs?
* [x] Did you check the Setup?

### Description

I can't open the Quick Picker. Very annoying. Furthermore, there isn't any entry in the keybinds JSON file. Thus, I can't even remove it.

I'm not even in an SQL file 👎

Why is this the case?

### Steps to Reproduce (For bugfixes)

1. Press and hold `Ctrl`
2. Press `E`

**Expected behavior:** [What you expected to happen]
Quik file picker opens

**Actual behavior:** [What actually happened]

This extension tells me:
>Can't execute query. You have selected nothing.

### Versions

- *Version*: (latest)
- *OS*: Windows

**Comment by mtxr** [comment]
Well, it doesn't look like a bug. 

It's just a matter of changing the keybindings. `CTRL+E` is the default keybinding since the beginning. You can just change it on your keybindings to anything else.

Since you have a custom behavior for `CTRL+E`, the conflict happens.

You can get the keybindings from the global keybindings file, paste into yours (user file) using another editor.

Let me know in case you need any help.
