### ISSUE TITLE
Reduce notifications

### ISSUE THREAD

**Issue by davidlwatsonjr** [mtxr/vscode-sqltools#128]
**Is your feature request related to a problem? Please describe.**
Every time I open VS Code, I get a notification about this extension.

**Describe the solution you'd like**
I would like to almost never get a notification about an extension. The experience is jarring and reduces the effectiveness of notifications. Notifications, IMO, should be reserved for instances where I must take action now.

**Describe alternatives you've considered**
The alternatives I see are to either fork this extension myself without the notifications or to just uninstall it. Considering I don't use it that often, I've opted to uninstall. When I need a tool like this in the future, I'll just have to find something then.

**Additional context**
I hope to not come off too negative here, because I do appreciate the work done on this project. But given that, at the time of this writing, there have been over 193,000 downloads of this extension and it only has 8 donators, 1 "supporter", and 1 contributor aside from its owner; I'd have to guess that a donation notification every time a user opens VS Code is just not effective. I would advise removing the annoyance and considering other avenues of fund-raising. The badges in the README are pretty common and not as annoying. I have no problem with those.

**Comment by mtxr** [comment]
Hi David, 

Sorry about that. But actually that happened this week because we had multiple releases.

The intention of the notification is not to get donations, but to tell users we had an update and read te changelog.

If you are really receiving a notification every time you open VSCode, it's a bug. Should be showing every time. Just once per release.

Could you confirm that for me please?

**Comment by mtxr** [comment]
I've added a rule to notify only if user has not been notified in the past 3 days.

As I told you, notifications are to notify about releases, not to get donations.

Also I've added an option to completely disable release notifications, `disableReleaseNotifications`.

So, please disable it if you think its annoying. Available on next release v0.16.9.

About you first comment, here is a little background:
The intention of this extension was to make my day more productive, allowing me to retire lots of tools for database management. That was Sublime Text version, and still for VSCode. I've been working on this project for more than 3 years, and was you said, I've received just a few donations and I have 1 registered patron. Why do I still work in this project? For sure it's not for the money. I like open sourcing, I've contributed to yarn, VSCode, reactive-search and other projects, I believe in open sourcing. But just a few open source projects can make money, extensions usually aren't.

Don't get me wrong but, I didn't think you were negative, but it's the second time I read an issue like this and I don't understand why to fork to remove a notification instead of contributing with a PR to improve how this notifications are being shown?
