### ISSUE TITLE
MSSQL - Trusted_Connection=True

### ISSUE THREAD

**Issue by spjeff** [mtxr/vscode-sqltools#129]
**Is your feature request related to a problem? Please describe.**
Create connection MSSQL requires a username/password for SQL text login.
Would like option for "Trusted_Connection=True" to login as current Windows user.  Single sign-on.  https://www.connectionstrings.com/sql-server/

**Describe the solution you'd like**
Create new connection checkbox "Trusted Connection" and user/password text boxes disappear.

**Describe alternatives you've considered**
None

**Additional context**
Helpful for Windows server admins to connect MSSQL with current user context.
More secure, avoid saving any credentials.

**Comment by mtxr** [comment]
Hi @spjeff. 

Please se #61 for some background about this issue.

I want to  support it, but I'll need to wait till VSCode team allows us to handle installation time deps. See [ VSCode Roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap#extension-authors), "Enable extensions to install additional platform specific components at extension installation time.". Issue Microsoft/vscode/issues/6929

It's in their roadmap, but no date for now.

Also this is just for windows, so would be great if we could wait them to complete this Microsoft/vscode/issues/23251 too.

So far, I don't think I can resolve this issue.

I already have PR #120 and #123 that I can't complete because of a similar problem.

If you see PR #120, if I can complete it, I'll be able to do the same for Trusted Connections here.

I'm glad you've opened this issues, it's pretty useful this feature, but for now, I just can ask you some patience, I can even guess a starting date to work on this issue. 

Are you able to use username and password for now? Otherwise suggest to use Microsoft MSSQL extension. It's very handy, but they have a bunch of engineers creating the language server in .NET, so I'm pretty sure it will work for you.

Thanks again!

**Comment by spjeff** [comment]
Excellent, thank you @mtxr

**Comment by yorkshirelandscape** [comment]
Is this still unsupported? VSCode seems to have closed the (dupe of) the issue in their repo, but I'm not seeing the option anywhere.

**Comment by gjsjohnmurray** [comment]
@yorkshirelandscape I don't think the MSSQL driver has been enhanced to support this.
