### ISSUE TITLE
[Feature request] cluttered database tree view 

### ISSUE THREAD

**Issue by callamaris** [mtxr/vscode-sqltools#139]
Hi,

please use the oracle system view user_tables instead of all_tables for the database panels.

unlike all_tables the system view user_tables shows only the tables owned by the connect user, which is the default behaviour of most oracle database clients.

The table list is pretty much unusable when connecting as an admin user, since the list can get so long on a big database that the scrolling causes wrist pain. In my case its >3000 tables with an admin user account.

an alternative to using user_tables could be grouping the tables by owner:
- Tables
   - user1
      - table1
      - table2
   - user2
      - table3
      - table4

**Comment by mickeypearce** [comment]
Hey @callamaris , thanks for the request.

As schemas are not yet supported (https://github.com/mtxr/vscode-sqltools/issues/71) I decided for `all_tables` as a compromise. Mainly because is useful to have all tables accessible to the current user at hand for example when working with autocomplete, etc.

But I also agree that tree view gets cluttered and also slows performance.

**Comment by mickeypearce** [comment]
@mtxr , @callamaris , does it makes sense to wait for the schema support?

**Comment by mtxr** [comment]
For sure! Thanks @mickeypearce.

After structuring explorer to support schemas, should be easy to do it.

Do you want to do it? Otherwise I'll take a shot on it in the weekend

**Comment by mickeypearce** [comment]
Please go ahead. :smile: I would then adjust the oracle dialect to the schemas support.

**Comment by julientype** [comment]
3000 tables .......   lol..... with sql Intel-a-scene  menus.... lol

**Comment by mickeypearce** [comment]
Changed to show only tables owned by current user https://github.com/mtxr/vscode-sqltools/pull/149
