### ISSUE TITLE
Error opening connection The "config.server" property is required and must be of type string.

### ISSUE THREAD

**Issue by u33aga** [mtxr/vscode-sqltools#356]
Error opening connection The "config.server" property is required and must be of type string.

{
  "name": "123",
  "dialect": "MSSQL",
  "connectString": "Data Source=123;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False",
  "connectionTimeout": 30
}

**Comment by mtxr** [comment]
This is fixed in another branch. Will be merged soon.

Anyway, maybe you will need to change your `connectString` to `Server={localhost,1433};Data Source=123;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False` for example.

I'll keep you posted
