### ISSUE TITLE
Please add the option to capitalize SQL keywords

### ISSUE THREAD

**Issue by odebroqueville** [mtxr/vscode-sqltools#357]
**Is your feature request related to a problem? Please describe.**
I saved the following statement in a query.sql file:
`select * from wakanda where alpha = 8 and beta = 9 limit 10;`

and then formatted it (btw, cmd+e cmd+b for OS X Mojave didn't do anything!) producing this result:
```
select
  *
from
  wakanda
where
  alpha = 8
  and beta = 9
limit
  10;
```

**Describe the solution you'd like**
I would very much have preferred the following result which I find more readable and compact:
```
SELECT *
FROM wakanda
WHERE alpha = 8
  AND beta = 9
LIMIT 10;
```

**Describe alternatives you've considered**
or at least capitalising the SQL keywords:
```
SELECT
  *
FROM
  wakanda
WHERE
  alpha = 8
  AND beta = 9
LIMIT
  10;
```

It would be really nice if you would add support for capitalisation, maybe as a setting.

**Comment by mtxr** [comment]
Hi @odebroqueville .

Actually keywords already have the option to transform to upper case. Take a look here: https://github.com/mtxr/vscode-sqltools/blob/084759a15f5152a05fec4f12579fae60ab247578/.test-database/.vscode/settings.json#L13

The formatting you suggested is pretty cool. We already have a ticket for that in the formatter project. I'll link it here after work.

Closing since we already have a ticket for this.
