### ISSUE TITLE
Connection string format for Postgres database for SSL connection using certificate.

### ISSUE THREAD

**Issue by ketan86** [mtxr/vscode-sqltools#374]
I could not find information on how to connect to Postgres database using ssl certs. 

There is no option for ssl certs on the settings page so was trying "connection string" option but that also does not work since i am not sure how exactly that connection string should be formatted. 
I want to provide following inputs: 
1. host
2. port
3. dbname
4. user
5. ca file
6. cert file
7. key file 
  
can anyone help ?

**Comment by mtxr** [comment]
@ketan86 you can pass driver specific settings like this:

```json
  {
    "name": "PGSQL",
    "server": "localhost",
    "dialect": "PostgreSQL",
    "port": 5433,
    "database": "test_db",
    "username": "root",
    "askForPassword": false,
    "password": "root",
    "connectionTimeout": 15,
    ...
    "pgOptions": {
      "ssl": {
        "rejectUnauthorized": false, // set to false if it's a self signed cert
        "ca": "<CA file contents>",
        "key": "KEY file contents>",
        "cert":"<CERT file contents>"
      }
    }
  },
```

More info: https://node-postgres.com/features/ssl

The only problem so far is that you need to put the file contents in the settings since there is no way we can read the files for you now.

in the future you will be able to use a path like `file:///path/to/cert/cert.crt` and we will read it before connecting.

**Comment by mtxr** [comment]
Closed in `vnext` branch.
