### ISSUE TITLE
SQLite connection demands password

### ISSUE THREAD

**Issue by T1mL3arn** [mtxr/vscode-sqltools#396]
**Describe the bug**

SQLite connection demands password.

**To Reproduce**

Execute command 'Add New Connection' and choose SQLite. You can see `askForPassword` setting is `true`. 

![sqlite pass](https://user-images.githubusercontent.com/9349164/65565215-9afcf880-df92-11e9-94bd-5327bd922ffd.jpg)

Also it forces vscode to prompt a password input dialog when testing connection (it accepts any password except an empty).

![passw input](https://user-images.githubusercontent.com/9349164/65566044-1069c880-df95-11e9-8f01-a886b4a17c03.jpg)

There is no need for a password for SQLite, that setting should be `false` by default.

**Desktop:**
 - SQLTools 0.21.0
 - VSCode 1.37.1
 - Dialect Used/Version: SQLite

**Comment by drk-mtr** [comment]
I just came along to log this and saw it's already captured.

Firstly - thank you for the brilliant plugin! I love not having to leave vscode and have found it really useful - and I really like a lot of the design choices that have been made.

I was a bit confused by this one. I like the fact that we get to see a summary of the json schema when adding the connection - however it would be brilliant if we had the ability to amend parameters in the json such as the password prompt - because otherwise reviewing this json (for something we don't have the ability to change) seems redundant.

I guess allowing people to edit the json schema might offer a nice vehicle for giving people new features without having to think about ui elements too - so it may offer other positives...

(p.s. I realize there's probably a json file lying around somewhere that I should just go and edit!)

**Comment by brandonlipman** [comment]
Is there a way to locally make this patch or best to wait for an update to roll out?

**Comment by mtxr** [comment]
If you remove `askForPassword` from your settings file, it will be working fine.

Anyway, I plan to release it today or tomorrow.
