### ISSUE TITLE
Support sql template literal in javascript?

### ISSUE THREAD

**Issue by voxpelli** [mtxr/vscode-sqltools#429]
I'm currently using https://github.com/ForbesLindesay/vscode-sql-template-literal to get syntax highlighting for sql template literals, but it would be nice to get the functionality of this extension in those places as well, and not only have it in `.sql` files.

Is this something you are planning to support, would consider to support (or already support, but I have somehow missed it)?

Thanks for a very well polished extension!

**Comment by mtxr** [comment]
Hi @voxpelli. I've use this extension as well. It's pretty cool.

So far I don't plan to add it soon. @ForbesLindesay has done a great job there so It's something that's already covered by his extension.

We could add this in the future for sure, but It would be better to add for at least most common programming languages to be valuable for a variety of users.

For now maybe it would be better to add a section in the README of extensions we can pair with to boost up our productivity. How does it sound? Since you also was looking for this feature (as I did too previously) we could help increasing its visibility to our users.
