### ISSUE TITLE
mysql with xprotocol: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by frankyjuang** [mtxr/vscode-sqltools#442]
**Describe the bug**

Connect to mysql 8.0 server with caching_sha2_password using xprotocol without password yields
`Error opening connection Cannot read property 'length' of undefined`

**To Reproduce**

My connection settings
```json
        {
            "askForPassword": false,
            "connectionTimeout": 30,
            "database": "test",
            "dialect": "MySQL",
            "name": "localhost",
            "port": 33060,
            "server": "localhost",
            "username": "root",
            "mysqlOptions": {"authProtocol": "xprotocol"}
        }
```

**Expected behavior**
Connection established.

**Desktop (please complete the following information):**
 - SQLTools Version: latest 0.21.2
 - VSCode Version: latest 1.40.0
 - Dialect Used/Version: mysql 8.0.18
 - OS: Mac Mojave

Happy to help fix this if anyone can point me a direction. Thanks

**Comment by mtxr** [comment]
Hi @frankyjuang .

You could fix this in this file:

https://github.com/mtxr/vscode-sqltools/blob/master/packages/core/dialect/mysql/xprotocol.ts#L14-L39

This fix should be probably a missing flag or property in this object.

If you know how to debug node in vscode (or node inspector), you should be able to quickly find where you should change.

`launch.json` is already set to be used with VSCode if you want.

Try to use this approach:

1. Clone the repository
2. do `yarn` inside of project root, when finished, `yarn run watch`
3. Open vscode, go to debugger sidebar activity and select to launch both extension and language server
4. Add some breakpoints to that file, you will start seeing some cools stuff.

than it's just playing around and reading some docs for this driver. You can find useful info here: https://dev.mysql.com/doc/x-devapi-userguide/en/database-connection-example.html
and here: https://dev.mysql.com/doc/dev/connector-nodejs/8.0/

Reach me out if you have any more questions.

PS: Sorry for the late reply, I'm writing quickly now because I'm bit busy but still want to provide you some guidance. Even though, don't hesitate to contact me :smile:

**Comment by mtxr** [comment]
@frankyjuang any luck?

**Comment by frankyjuang** [comment]
sorry a bit tight these days. will try this weekend

Matheus Teixeira <notifications@github.com> 於 2019年11月15日 週五 下午12:03寫道：

**Comment by frankyjuang** [comment]
@mtxr oh my bad. Realized that i have to provide a empty string for password. Misunderstood the meaning of `askForPassword`. But still ran into another issue which is already filed here https://github.com/mtxr/vscode-sqltools/issues/447
