### ISSUE TITLE
Oracle connection string does not work

### ISSUE THREAD

**Issue by BuZZ-dEE** [mtxr/vscode-sqltools#457]
I can not connect to an Oracle DB using the connection string method. I use the following connection string:

```
"connectString": "(DESCRIPTION=(ADDRESS_LIST=(FAILOVER=ON)(LOAD_BALANCE=OFF)(ADDRESS=(PROTOCOL=TCP)(HOST=db01-1.dbserver.lan)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=db02-1.dbserver.lan)(PORT=1521)))(CONNECT_DATA=(FAILOVER_MODE=(TYPE=select)(METHOD=basic)(RETRIES=180)(DELAY=1))(SERVER=dedicated)(SERVICE_NAME=ocdb)))" 
```
I get the following error message:
> Error opening connection ORA-12169: TNS:Net service name given as connect identifier is too long

 - SQLTools Version 0.21.3
 - VSCode Version: 1.40.2
 - Driver Used/Version: Don't know
 - OS: Arch Linux

**Comment by apj68** [comment]
I tried the extended connection like this:
```
        {
            "name": "MyConnName"
            ,"driver": "OracleDB"
            ,"database": "MBBXX"
            ,"password": "mypasswd"
            ,"username": "MBBUSER"
            ,"askForPassword": false
            ,"connectionTimeout": 15
            ,"server": "myservername"
            ,"port": 1521
        }
```
And I get:
```
    Error selecting connection Request connection/ConnectRequest failed with message: Cannot read property 'getId' of null
```
The logs don't say much:
```
    DEBUG: Settings updated!
    INFO: Executing SQLTools.getConnectionStatus
    DEBUG: Connection explorer updated.
    INFO: Executing SQLTools.selectConnection
    INFO: Executing SQLTools.getConnectionStatus
    INFO: Executing SQLTools.getConnectionStatus
    INFO: Executing SQLTools.getConnectionStatus
    INFO: Executing SQLTools.getConnectionStatus
    INFO: Executing SQLTools.getConnectionStatus
```

Would love to have a settings file example.  I'm not sure if something went wrong with my installation but I had no settings file and cannot find anything in the docs on whether there are required entries.

**Comment by mickeypearce** [comment]
Here is Oracle Start Guide: https://vscode-sqltools.mteixeira.dev/driver/oracle, although your connection settings seems allright. Did you try reloading VS Code?

**Comment by mickeypearce** [comment]
@BuZZ-dEE : Can you please confirm if your "connectString" works with SQL Developer or similar tool you usually use to connect to DB?

**Comment by BuZZ-dEE** [comment]
@mickeypearce yes, I use that connection string:

```
jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(FAILOVER=ON)(LOAD_BALANCE=OFF)(ADDRESS=(PROTOCOL=TCP)(HOST=db01-1.dbserver.lan)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=db02-1.dbserver.lan)(PORT=1521)))(CONNECT_DATA=(FAILOVER_MODE=(TYPE=select)(METHOD=basic)(RETRIES=180)(DELAY=1))(SERVER=dedicated)(SERVICE_NAME=ocdb)))
```

also in DBeaver and it works.

**Comment by mickeypearce** [comment]
Maybe try creating a "Net Service Name" as suggested in: https://oracle.github.io/node-oracledb/doc/api.html#-1424-jdbc-and-oracle-sql-developer-connection-strings.

**Comment by mickeypearce** [comment]
I tried connecting with connections identifier ("connectString") which is quite larger in my case (I usually connect with alias) but unfortunatelly I cannot reproduce.

**Comment by apj68** [comment]
@mickeypearce, thanks for your reponse.  Yes, I tried reloading vscode.  I also tried the "Net Service Name" approach.  For some reason, I have a feeling it's not even getting to the actual connection attempt rather it's failing for some other reason.  That's why I thought something about the `settings.json` was wrong.

**Comment by mickeypearce** [comment]
Did you use "New connection" command or manually or you manually edited settings.json file?

**Comment by apj68** [comment]
@mickeypearce, I manually edited `settings.json`.  I just tried from the new connection command.  I used the "server/port" option and when I tried to test the connection it gave me:
```
Request connection/TestConnectionRequest failed with message: Cannot convert undefined or null to object
```
I'll try other connection options and see what happens.

**Comment by apj68** [comment]
I tried with `connectString` and I get the same message.  Another thing: after saving it gives me an option to "Connect Now" but when I click Connect Now (from the preview screen) it takes me to the new connection creation page.  Also, I'm not sure where it's saving it because I don't see any new files in `.vscode` .

**Comment by apj68** [comment]
@mickeypearce , I'm connected!  I deleted the existing `settings.json` and then use the connection wizard.  From here I started getting different errors, first that `nodejs` was a dependency, then `oracledb`.  Once those were resolved, I tried the connection and found that for the `server/port` connection type I had to use `service name` rather than `database name`.  Now it's looking good, thank you.

**Comment by apj68** [comment]
Hmm.. Now when I highlight a region and run `SQLTools: Run Query` it asks me to enter the query.  Ugh.

**Comment by mickeypearce** [comment]
If you'd like to execute a selection there is a different command: "Run Selected Query".
