### ISSUE TITLE
Encryption/hashing of credentials in settings

### ISSUE THREAD

**Issue by Fmstrat** [mtxr/vscode-sqltools#479]
**Is your feature request related to a problem? Please describe.**
When saving connections, usernames and passwords are displayed in plain text.

**Describe the solution you'd like**
Allow the use of a master password (unsaved) that will decrpyt the settings variables in memory.

**Describe alternatives you've considered**
n/a

**Additional context**
This would allow for storing `settings.json` in Git.

**Comment by aaronsteers** [comment]
I came here looking for something similar. My similar idea was to store in `.env` files and map into the settings file using environment variables. 

Are there any other workaround available as of today to keep creds out of `settings.json`?

I have not tried this yet, but the only other workaround I could think of was to store the same info in the users' `settings.json`, rather than in the workspace one. Thoughts?

UPDATE: Oops, I didn't think of settings sync. Yikes, definitely not a good idea to sync creds up to a gist:

From #210:

> Would it be possible to store connections somewhere else than in the config of VSCode? I sync my settings with a public gist and I don't want production credentials in there.

**Comment by DaveParr** [comment]
I recently came back to try SQLtools because I couldn't remember why I stopped around 2018. 

Love everything else that has been done on this project, but this will be likely why it doesn't stick with me again. Sorry :/

**Comment by gjsjohnmurray** [comment]
Closing in favour of #927
