### ISSUE TITLE
Doesn't allow create TEMPORARY TABLE

### ISSUE THREAD

**Issue by hevzy86** [mtxr/vscode-sqltools#504]
Extension is amazing, just Doesn't allow create TEMPORARY TABLE

**Comment by mtxr** [comment]
What do you mean?

Which driver are you talking about?
The extension needs to be connected to some driver to display/create tables.

As is, this issues doesn't give me any tip on what you are requesting 🤔

**Comment by realDavidBlowie** [comment]
@mtxr To reproduce this problem:

1. Create temp table using single query run (Cmd + E x2)
2. Run query unrelated to temp table using single query run
3. Select from temp table using single query run.

Step 3 will fail if step 2 came before it. Temp table cannot be accessed since it probably lives in a different session or something.
