### ISSUE TITLE
Unable to bookmark

### ISSUE THREAD

**Issue by prashantsharma** [mtxr/vscode-sqltools#566]
**Describe the bug**
I am not getting the option to create a bookmark.

**To Reproduce**
1. Go to 'SQLTools'
2. Click on 'Bookmark section'

**Expected behavior**
Should be able to bookmark

**Screenshots**
NA.

**Desktop (please complete the following information):**
 - SQLTools Version [v0.21.7]
 - VSCode Version: [1.45.1]
 - Driver Used/Version: [MySQL 5.6]
 - OS: [Mac]

**Additional context**

**Comment by HalfBottleOfMind** [comment]
Hi. Hit same issue. Found answer here #50.

**Comment by mtxr** [comment]
@prashantsharma  You are expecting this to be on the explorer side bar?

**Comment by mtxr** [comment]
I've just added the add button to the bookmarks view:
![image](https://user-images.githubusercontent.com/707561/83988238-12a06700-a919-11ea-98b2-4e11f06f599a.png)
Also, you can you the command palette to find the `Bookmark selected query` and the options is available in the context menu as well. **Remeber that you need to have something selected, otherwise the option on be shown.**

**Comment by prashantsharma** [comment]
@mtxr , Thanks I will check and let you know in case I face any issues.

**Comment by prashantsharma** [comment]
@mtxr, I am able to bookmark and running queries from bookmarks. Thanks.

But a new problem with my other machine. it didn't find a driver. Earlier I was able to see all the database icons.

![Screenshot 2020-06-08 at 11 00 52 AM](https://user-images.githubusercontent.com/1440232/83995791-01d30e00-a978-11ea-9f54-e01d4a7b8a6a.png)

**Comment by mtxr** [comment]
If you click to search for drivers, can you confirm they are all installed?
