### ISSUE TITLE
[Feature Request] Add Config Option for SQL Formatting

### ISSUE THREAD

**Issue by GaryFurash** [mtxr/vscode-sqltools#6]
different formatting options like http://www.dpriver.com/pp/sqlformat.htm

**Comment by mtxr** [comment]
I like the idea. Will be developed in a near future but connections comes first, ok?

**Comment by xinshangshangxin** [comment]
current status?

**Comment by mtxr** [comment]
Stuck. Help wanted

**Comment by mtxr** [comment]
I'm closing this issue because it there are no good enough JS libraries supporting all those features.

I plan to implement some of them, but not all. This is more like a prettier plugin that I could use than a feature of the extension.

Would be great to have, but it's a bit out of scope since some similar tools for database management also doesn't have it by default.

For now, I've added option to change reserved words case that it's more common and requested around the web.
