### ISSUE TITLE
Unable to view schema for Redshift

### ISSUE THREAD

**Issue by rjshanahan** [mtxr/vscode-sqltools#604]
**Describe the bug**
Prior to latest release of VS Code/SQLTools I was able to view the schema of my Redshift database. Since the upgrade this is longer visible in the SQLTools menu - "Nothing here" text is displayed - see below.

![image](https://user-images.githubusercontent.com/6904487/83610574-ce326580-a5be-11ea-84dd-8a4e1154b5ed.png)

**To Reproduce**
1. create Redshift connection
2. connect to Redshift instance using the SQLTools `Connections` menu
3. expand database within connection
4. expand `Schema` within connection - "Nothing here" is displayed instead of a list of tables.

**Expected behavior**
Expanding the `Schema` option within a db connection allows users to see tables within the schema

**Desktop (please complete the following information):**
 - SQLTools Version 0.22.3 (issue first appeared on 0.22.2)
 - VSCode Version: 1.45.1
 - Driver Used/Version: SQLTools PostgresSQL/Redshift Driver 0.0.3
 - OS: Windows

**Comment by mtxr** [comment]
@rjshanahan can you try to manually run this query:

https://github.com/mtxr/vscode-sqltools/blob/134e38769adf6f7ffe79b5dd84cdf12a9bfcc058/packages/driver.pg/src/ls/queries.ts#L207

Of course, changing to valid values, let me know if you get any errors

**Comment by rjshanahan** [comment]
No errors @mtxr ; however, no data returned either.

That said, no results are returned from `information_schema.schemata` ie. `select * from information_schema.schemata limit 10;'

**Comment by mtxr** [comment]
what's your postgres version and whats the name of schema?

**Comment by rjshanahan** [comment]
Here's the version info: `PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.15896`.

There's nothing weird in the schema name, eg. `abcdef`.

**Comment by mtxr** [comment]
Do you still have this issue on recent releases of the driver and the extension?

**Comment by Meyfarth** [comment]
Hello!

I didn't use the plugin for some time and the driver just got updated. Now I see way less schemas than before.

The data engineer told me that it looks like I only see schemas that the user I'm connected with is owner, even though I'm supposed to see all. Maybe you can check in here?

**Comment by JunkMyFunk** [comment]
I'm also experiencing this issue - the schemas listed are only those owned by the current user. I would expect to see all of the schemas shown when running `\dn` on a psql client logged in as the same user.

**Comment by aniruddha-pe** [comment]
Any resolutions to this ?

**Comment by cacrespo** [comment]
The same problem!

**Comment by ashish10alex** [comment]
Im having the same issue

**Comment by andrewf13tcher** [comment]
Same issue here.

Version
---------
Redshift:
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.21262

VSCode:
1.51.1

SQLTools:
0.23.0

**Comment by DCToddM** [comment]
Have we got a fix for this problem?  I'm experiencing the same problem.

**Comment by sgottipati-cuda** [comment]
seeing same issue. Is there a fix or workaround for this?

**Comment by longhowlam** [comment]
having same issue,

**Comment by JianJenniferGong** [comment]
Same issue here

**Comment by kj-9** [comment]
> @rjshanahan can you try to manually run this query:
> 
> https://github.com/mtxr/vscode-sqltools/blob/134e38769adf6f7ffe79b5dd84cdf12a9bfcc058/packages/driver.pg/src/ls/queries.ts#L207
> 
> Of course, changing to valid values, let me know if you get any errors

I checked `information_schema.schemata` and it only returns schemas that my user owns. It seems AWS changed the behavior at some point of time.

I also tired to replace that query and I look trough some options. I'm happy if this summary helps:
1. Use `pg_*` tables which [seems more supported by AWS](https://docs.aws.amazon.com/redshift/latest/dg/c_join_PG.html)
2. Use redshift-specific system views as mentioned [here].(https://docs.aws.amazon.com/redshift/latest/dg/c_join_PG_examples.html).
3. Use `information_schema.tables` instead and make result rows distinct.

I think option1 is the most simple way, but unfortunately I could not find way to relate database names and schema names only using `pg_*` tables so far.

option2 may be the more reliable than option3, because there is an official documentation in AWS webpage. The downside is that it will break compatibility with postgres, requires an additional logic (I'm not sure because I'm new to SQLtools).

option3 is easy fix, I found it works in my redshift cluster and compatible with postgres test env. So I can send the pull request. It introduces distinct operation, but will not significantly effect performance I think.

Now, need some discussion around these options?

ps. just my personal view, I feel redshift starts to deviate a bit from postgres. e.g. redshift now has external tables which postgres does not have, and these external tables are not shown in SQL tools(I will create issue for that). So they becaming different things, we might need separete logics for redshift and postgres in the future?

**Comment by kj-9** [comment]
Because the maintainer seems busy currently, I published [the quick fix version](https://marketplace.visualstudio.com/items?itemName=kj.sqltools-driver-redshift) of redshift driver for this issue. If anyone want the quick fix for this issue (like me), please use this extention.

Dear @mtxr,
As soon as this issue is solved for current PostgreSQL driver, I will unpublish this driver.

**Comment by mtxr** [comment]
@kj-9 thanks for the help. In fact I've been very busy, and I just saw your previous comment.

I see you published the extension specific for redshift, and my personal opinion is that you did good and it's better to have extensions individually prepared for each systems, so in this case, I'ld like to propose you to keep your project, and get it even deeper on Redshift specifics.

What do you say?

In want to spend more time in the future on the extension tooling itself rather than drivers. There are so many dialects that's it hard for me to maintain alone. Also, there's no way to master all those dialects, so I'ld stick preferbably with those I usually daily in my job. Funny fact: I've been using firestore now and I do miss using SQLTools, I've even started a side project to add firestore as a driver :laughing: 

So if you want, let's keep your extension, we can change the icon for the other driver to PG only and announce yours as a drop in replacement for Redshift.

Let me know and thank you again for releasing the project.

PS: For the users, i'm sorry i couldn't take over this, with this covid thing around there I had to focus on some family stuff for while. I'll be back as soon as my kid is back to school and my wife gets back working

**Comment by kj-9** [comment]
@mtxr thank you for your reply.

It is fine for me to keep my redshift driver separate from the PostgreSQL driver.

> we can change the icon for the other driver to PG only and announce yours as a drop in replacement for Redshift.

This will be nice information for users. It is bit confusing that there are two drivers for redshift for now.  
Is this should be another issue? Tell me if I can help for doing this.

I agree with you that there are too many databases for one person to follow. I cannot believe that you maintained so many drivers so far!

**Comment by mtxr** [comment]
@kj-9 can you create a repo. for your driver? then I can update the docs here to give the users instructions to install and use your driver instead of the PG one.

**Comment by kj-9** [comment]
@mtxr Sorry to keep you waiting. it took some time to refactoring my entire sqltools forked repo as a standalone redshift driver one. [Here](https://github.com/kj-9/sqltools-redshift-driver) it is.

**Comment by kbec** [comment]
Any confirmation on this solution?

I wiped extensions and restarted VS Code to start fresh. Installed SQLTools v0.23.0 and Redshift Driver (Dedicated ver) v0.0.2.

Attempting to connect, I see the following.
![image](https://user-images.githubusercontent.com/46684748/119206567-1ad9af80-ba61-11eb-9469-266288c2fba4.png)

Do both drivers need to be installed?
Assuming yes, I installed SQLTools PostgreSQL/Redshift Driver v0.2.0.

I'm able to connect successfully, but I'm still seeing the same result:
![image](https://user-images.githubusercontent.com/46684748/119206921-1792f380-ba62-11eb-9ace-34c4ac809b10.png)

SQLTools output:
```
[1621639715936] INFO  (ext): EXECUTING COMMAND => sqltools.selectConnection
[1621639715936] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1621639715937] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1621639715937] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1621639715938] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1621639715938] INFO  (ls): REQUEST RECEIVED => connection/ConnectRequest
[1621639715939] INFO  (ls): Connection instance created for redshift.vacasa.warehouse.
    ns: "conn-manager"
[1621639716437] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1621639716448] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1621639716448] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1621639716467] INFO  (ext): EXECUTING COMMAND => sqltools.getChildrenForTreeItem
[1621639716467] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1621639716468] INFO  (ls): REQUEST RECEIVED => connection/GetChildrenForTreeItemRequest
[1621639716468] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1621639716468] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1621639716469] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1621639716469] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1621639716471] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1621639716471] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1621639716473] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1621639716473] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1621639716474] INFO  (ext): Connection explorer changed. Will be updated.
    ns: "conn-man:explorer"
[1621639716683] INFO  (ext): EXECUTING COMMAND => sqltools.getConnections
[1621639716684] INFO  (ls): REQUEST RECEIVED => connection/GetConnectionsRequest
[1621639716710] INFO  (ext): EXECUTING COMMAND => sqltools.getChildrenForTreeItem
[1621639716711] INFO  (ls): REQUEST RECEIVED => connection/GetChildrenForTreeItemRequest
```

VS Code: 1.56.2
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
OS: Windows 10 (19041)


Wondering if I'm missing something or if the solution is still in work. Any additional info I can provide?

**Comment by kj-9** [comment]
Hi @dudeKB 
No, you don't need two drivers.
Perhaps you are trying using dedcated driver with  a PostgreSQL/Redshift Driver connection config.

Can you check that you created and using the config for dedicated driver?
You can create it with "Add new connection" -> clicking below.

![image](https://user-images.githubusercontent.com/46800811/119282729-b5aad780-bc75-11eb-8305-bf50f94a802d.png)

**Comment by kbec** [comment]
Ok, that makes sense - and totally fixes the issue. I figured I had just skipped a step somewhere.

Thanks @kj-9 for the quick response! And thanks to all for your work on this!

**Comment by gjsjohnmurray** [comment]
Closing with recommendation to use the dedicated Redshift driver from https://marketplace.visualstudio.com/items?itemName=kj.sqltools-driver-redshift
