### ISSUE TITLE
problems with formatting and lens

### ISSUE THREAD

**Issue by xenoterracide** [mtxr/vscode-sqltools#618]
not sure if this is a bug or a file only setting, every time I put a newline between some statements/comments, and save (kicking in the formatter) it removes all newlines. Possibly related, the "select block" always selects everything

sqltools 0.22.7.
postgres 0.0.5
```
> code --version                                                                                 # service-db-main-migration -> develop $ ! ?
1.46.0
a5d1cc28bb5da32ec67e86cc50f84c67cc690321
x64
> uname -a                                                                                       # service-db-main-migration -> develop $ ! ?
Darwin Calebs-MBP 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
>      
```

**Comment by mtxr** [comment]
You can use `sqltools.format` to set `lineBetweenQueries` prop to preserve or to use a few lines after you query end delimiter. See https://vscode-sqltools.mteixeira.dev/settings#sqltools.format.

But in any situation, you need to have `;` in the end of your queries. SQLTools doesn't change your query nor parses multiple queries without `;` because we don't have a full parser implemented yet, so the only way to select blocks/queries or highlights it is with selections or using delimiter. This behavior is the same we see on psql cli for example if we try to run a query without the delimiter, and I don't see why we should change it. Closing
