### ISSUE TITLE
Set result tab name as block name

### ISSUE THREAD

**Issue by samueldefilippo** [mtxr/vscode-sqltools#635]

**Comment by joefru** [comment]
I'm assuming @samueldefilippo means that when you have some sql defined like this (from docs)...

```
-- @block create company table
-- @conn PGSQL
CREATE TABLE IF NOT EXISTS COMPANY(
    ID INT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    AGE INT NOT NULL,
    ADDRESS CHAR(50),
    SALARY REAL
);

INSERT INTO COMPANY VALUES (1, 'Name', 12, 'address', 0.2);

-- @block create department table
CREATE TABLE IF NOT EXISTS DEPARTMENT(
    ID INT PRIMARY KEY NOT NULL,
    DEPT CHAR(50) NOT NULL,
    EMP_ID INT NOT NULL
);
```

...then the result tab names should be _**create company table**_ and _**create department table**_, respectively.

Currently, the tab name appears to be the entire text of the query block, which makes it difficult to quickly navigate open result tabs.

This would pair nicely with Issue #632 so that re-running queries in named blocks would be the method for reusing result tabs. Then, a new setting wouldn't be required for toggling tab reuse.

Additionally, I'd suggest including the connection name in the tab name as well. To continue the example above, it would be something like _**PGSQL: create company table**_ and _**Active Connection: create department table**_.

_(BTW, great job on the extension. Best SQL extension I've come across.)_
