### ISSUE TITLE
will this support presto driver?

### ISSUE THREAD

**Issue by kekeadou** [mtxr/vscode-sqltools#652]
Hi, I'm wondering if sqltools will support presto driver recently? or how can I get it work on my own?
I'm new to vscode + sqltools, but i really like it.
Any advice will help, thanks.

**Comment by mtxr** [comment]
hey @kekeadou , depends. Someone needs to implement the driver. I'm not familiar with Presto, so I can't tell you I'ld support it now. Although anyone can implement this following this guide: https://vscode-sqltools.mteixeira.dev/contributing/support-new-drivers

I'll close this issue since I can't support it now, but anyone interested in developing it can reach out to me and I'll provide some assistance.
