### ISSUE TITLE
How to become an official driver 

### ISSUE THREAD

**Issue by isc-rsingh** [mtxr/vscode-sqltools#683]
Hi @mtxr. As you know @daimor has done a lot of work on the InterSystems driver and contributed to the overall project. This work was done with funding from InterSystems, so I think that would qualify it to have "official driver" status on the VS Code Marketplace. It is definitely blessed by the company itself. 

thanks,
Raj

**Comment by mtxr** [comment]
Hi @rajrsingh, yeah, I saw the extension and it's impressive his work! Thanks, @daimor!

About the question to become an official driver, I was considering official drivers everything under this repository and mainly maintained by me. I don't know if that's the correct name for that, but the idea to create the plugin API was to allow more developers to create drivers and release in their pace. I've been very busy and has been hard to keep working on the project and at the same pace that I was before, so that's why I did the API.

"Community drivers" was the name I've found to mention drivers created by others, but since InterSystems driver has the company bless, we can create a section *Company Drivers* or another name that fits better for this, or we could just remove this distinction and have a table with the links and maintainers for each driver. what are your thoughts on this?

I'm open to suggestions and I'm counting on you on that. Since the plugin api was released recently, all this still fresh and I don't have any final decisions about the whole ecosystem 😄

Thanks!

**Comment by mtxr** [comment]
@rajrsingh @daimor any suggestions about this? otherwise, I'll close or move this discussion somewhere else

**Comment by rajrsingh** [comment]
Thanks for the nudge @mtxr. I think it's important to let users know which drivers are more likely to be high quality and maintained, because that helps them choose which ones to use. I think we all have had the experience of committing time and effort to learn and use something, only to find out the developer who built it only ensured it worked for their purposes and has lost interest in maintaining it. I like the term "official drivers", but even more importantly is to use the ability to recommend installing some drivers automatically after installing SQLTools. I want it to be as obvious as possible to see that you can use it with InterSystems' databases!

**Comment by mtxr** [comment]
@isc-rsingh can you open a PR to mark your driver as official like you mentioned before? It could be another name that you think it's better.. I still don't have a final opinion about the name, so I'll leave it up to you.

Thanks again guys

**Comment by isc-rsingh** [comment]
@mtxr I can't remember if the install process for "official drivers" used to be different, but now it seems that all drivers are on equal footing, and the difference is whether the code is part of your project or separate, so I think it makes sense to keep things exactly as they are now.
