### ISSUE TITLE
yarn install @sqltools/extension fails on: "Error installing vscode.d.ts: Error: Request returned status code: 404 while"

### ISSUE THREAD

**Issue by offer8** [mtxr/vscode-sqltools#783]
Hi @mtxr ,

**Describe the bug**
yarn install of plugin started to fails in version **0.21.8**.

**To Reproduce**
We have a DOCKER image which builds the sqltools extension:

```
ARG VSCODE_SQLTOOLS_VERSION=0.21.8

RUN git clone --branch v${VSCODE_SQLTOOLS_VERSION} https://github.com/mtxr/vscode-sqltools.git &&  cd vscode-sqltools && git checkout -b vscode_sqltools && \
    # get dependencies
    yarn && git submodule update --init --recursive && yarn workspace @sqltools/formatter install && \
    # build
    npm install -g cross-env && ${NODE_PATH}/cross-env NODE_ENV=production yarn workspace @sqltools/formatter build && \
    ${NODE_PATH}/cross-env NODE_ENV=production yarn workspace @sqltools/extension run compile && cd .. && \

```

Since last week it started to fail on:

```
**error /source/vscode-sqltools/node_modules/@sqltools/extension: Command failed.**
Exit code: 1
Command: yarn run vscode-install
Arguments: 
Directory: /source/vscode-sqltools/node_modules/@sqltools/extension
Output:
yarn run v1.22.5
warning @sqltools/extension@0.21.8: The engine "vscode" appears to be invalid.
$ /source/vscode-sqltools/node_modules/.bin/vscode-install
Detected VS Code engine version: ^1.36.0
**Error installing vscode.d.ts: Error: Request returned status code: 404**
Details: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/releases/stable</pre>
</body>
</html>
```

Could you please assist?

**Comment by mtxr** [comment]
this has nothing to do with the extension.

If yout check `/source/vscode-sqltools/node_modules/.bin/vscode-install` file you will see it requests some microsoft servers and those are returning 404.

There's a long time I don't support the v0.21.x branches, so I'm not up to date with recent changes on vscode api for those versions.

As seen here https://github.com/microsoft/vscode/issues/62429 microsoft updated the url https://vscode-update.azurewebsites.net/api/releases/stable to https://update.code.visualstudio.com/api/releases/stable

That's what I've found so far.

Hope it helps, I'm closing this issue since it's unrelated and for a no longer supported version.


@offer8, But I'm curious about the reasons to be using this old version, would you mind answering?

Thanks in advance
