### ISSUE TITLE
Keyboard shortcut to run queries

### ISSUE THREAD

**Issue by manoranjanpanigrahi** [mtxr/vscode-sqltools#876]
hii , is there a keyboard shortcut to run all the queries from keyboard. otherwise every time I have to click on 'run on active connection'.

**Comment by gimbo** [comment]
If you look at the extension's page within VSCode (i.e. run the command "View: Show Extensions" to get the extensions list in the left-hand sidebar, and then find SQLTools in there), there's a "Feature Contributions" tab on that page, which shows all of the settings and commands for the extension (all extensions have this, it's a very handy reference).

Under "Commands" there are several relating to running queries, although they have somewhat inconsistent naming, and the descriptions aren't _brilliant_.

Right now, I have:

| Name | Description |
|--|--|
| `sqltools.runFromBookmarks` | Run |
| `sqltools.runFromHistory` | Run |
| `sqltools.executeCurrentQuery` | Run Current Query |
| `sqltools.executeQuery` | Run Selected Query |
| `sqltools.executeQueryFromFile` | Run This File |
| `sqltools.executeFromInput` | Run Query |

So you should be able to run any of those via the command menu. I find "Run This File" and "Run Current Query" most useful — the former runs all the queries in the current file, and the latter runs the query your cursor is within.

You can set up keyboard shortcuts for all of this too,  of course. I assigned `⌘E ⌘F` to "Run This File" and I reassigned  `⌘E ⌘E` from "Run Selected Query" (which I don't find useful as there's no quick keyboard-friendly way to select a query) to "Run Current Query". You can do those tweaks via the Keyboard Shortcuts editor, but I just dropped this directly into my `keybindings.json` for the same effect:

```
  {
    "key": "cmd+e cmd+f",
    "command": "sqltools.executeQueryFromFile",
    "when": "editorTextFocus"
  },
  {
    "key": "cmd+e cmd+e",
    "command": "-sqltools.executeQuery",
    "when": "editorTextFocus"
  },
  {
    "key": "cmd+e cmd+e",
    "command": "sqltools.executeCurrentQuery",
    "when": "editorTextFocus"
  },
```

Since you're asking 

> is there a keyboard shortcut to run all the queries from keyboard

I'd hope that either of those two would meet your need there.

Hope this helps!

**Comment by gjsjohnmurray** [comment]
@gimbo thanks for contributing that information.

**Comment by bombillazo** [comment]
Whats is the difference between these?
- Run Query
- Run Current Query

I understand that `Run Selected Query` should run what ever text is highlighted in the editor as SQL, `Run This File` runs the complete file but the 2 above I don't know the difference.

**_Nevermind_**, it was that Run Query will prompt you to enter a query as soon as you select the command. Run Current Query I think runs whatever your cursor is pointed at in the open file.

**Comment by BunnyMan1** [comment]
Here's my shortcuts configuration:

```
{
  "key": "cmd+r",
  "command": "sqltools.executeQueryFromFile",
  "when": "editorTextFocus && editorLangId == 'sql'",
},
{
  "key": "cmd+r",
  "command": "sqltools.executeQuery",
  "when": "editorTextFocus && editorLangId == 'sql' && editorHasSelection == true",
},
{
  "key": "cmd+shift+r",
  "command": "sqltools.executeCurrentQuery",
  "when": "editorTextFocus && editorLangId == 'sql'",
}
```

1. Pressing `CMD + R` will execute all the queries in the current file.
2. Pressing `CMD + R` when having some text selected will execute only the selected text.
3. Pressing `CMD + Shift + R` executes the current nearest single query.

This configuration is similar to how the Navicat Database tool query editor works.

**Comment by MaximSat** [comment]
I still dont understand how can I insert this to the settings json. Gave an extended example please

**Comment by gjsjohnmurray** [comment]
This belongs in keybindings.json 

Please use the advice at https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by juhaszp95** [comment]
I have a related but slightly different question - in a Jupyter notebook in VS Code I can set the cell language to be SQL and then I have the option to click above the cell to run on active connection. However, if I just do Ctrl+Enter, it tries to run it as if it's Python code (see below). Is there a way to bind Ctrl+Enter to 'Run on active connection' if the language is SQL?

<img width="464" height="231" alt="Image" src="https://github.com/user-attachments/assets/94710b39-0a81-4bdd-a0b9-1434dfbbbd3f" />

**Comment by gjsjohnmurray** [comment]
@juhaszp95 maybe you could add another condition to this when-clause:

<img width="2061" height="241" alt="Image" src="https://github.com/user-attachments/assets/dad82379-42fd-4bec-8d30-f79af078a3d2" />

**Comment by juhaszp95** [comment]
That's fine, but I haven't been able to find what command would run the cell in the first place. The following was the closest I've got (from above):
```
    {
        "key": "ctrl+e ctrl+e",
        "command": "sqltools.executeCurrentQuery",
        "when": "editorTextFocus && editorLangId == 'sql'",
    }
```
It tries to run something, but it runs an empty query, and hence returns an error. I.e. I'm looking for how to run a query with any keyboard shortcut in the first place, and then it would be nice to bind it to Ctrl+Enter as with python.
