### ISSUE TITLE
Tracking users without their permission

### ISSUE THREAD

**Issue by alexdor** [mtxr/vscode-sqltools#90]
Why is the telemetry enabled by default?

According to GDPR in order to collect the data of European users, the user has to opt-in. Tracking European users without their permission is illegal.

**Comment by mtxr** [comment]
This was developer before this GDPR global wave. I didnt have time to change it, but I'll change it today.

**Comment by mtxr** [comment]
Published

**Comment by alexdor** [comment]
Thanks for the quick response : )

**Comment by maxnordlund** [comment]
It still says "Help SQLTools development. You can opt-out any time.", default `true` on the settings page https://vscode-sqltools.mteixeira.dev/settings##sqltools.telemetry

On a fresh install this indeed defaults to `true`, which as pointed out is not GDPR compliant.

Also, it would be nice if this respected the global `telemetry.enableTelemetry` settings, like all MS extension and GitLens.

**Comment by mtxr** [comment]
@maxnordlund do you want to submit a PR for this?

By the way, telemetry is currently disabled in the last published version as you can see here https://github.com/mtxr/vscode-sqltools/blob/v0.21.x/packages/core/utils/telemetry.ts#L121

since I'm working on v0.22 and I still don't have defined what can be tracked/useful or not, it's disabled. But for sure we should use the global setting.

So if you want  to help, can you submit this change to master branch?
