### ISSUE TITLE
Remove AWS Redshift from Official Drivers list

### ISSUE THREAD

**Issue by gjsjohnmurray** [mtxr/vscode-sqltools#956]
The page at https://vscode-sqltools.mteixeira.dev/src-content-current-drivers first points AWS RedShift users at the official pg driver, then later mentions the community driver.

I think we should drop the first pointer in favour of the second. The dedicated RedShift driver is able to deal with issues such as #604.

Also remove it from README of main extension and from keywords in driver.pg/package.json

Retain it as an alias in driver.pg/src/constants.ts so existing connection definitions still work.

@mtxr what you think of this proposal?

**Comment by mtxr** [comment]
makes perfect sense to me @gjsjohnmurray . let's go for it. 

The more we can focus on the extension the best. The community should be the best source to support the drivers since they will have most of its knowledge considering the amount of db types existing out there. Since we already have a PG driver, let's make this one the "official" version from now on. Before we make this official, let's check with the maintainer.


@kj-9 in this case, is this something of your interest? Is there anything we can do to help?
We can update all docs to ditch the current driver we have in favor of yours, have links to your docs or even bring your docs here if you prefer.

Let us know.

**Comment by kj-9** [comment]
Hi, thanks for mentioning me.

I'm completely fine with removing the redsfhit driver from the SQLtools document. Other than that, I have no paricular wishes for updating SQLtools documentation in favor of the dedicated version.

 But let me know if there is anything I can help.
